ansible_ssh_host_key_checking: False
local_user: "{{ansible_user}}"
loggedIn_user: vagrant
dockerComposeVersion: 1.23.2
dockerComposeInstallPath: /usr/local/bin/docker-compose
dockerRegistryDomain: "192.168.56.89"
dockerRegistryInsecurePort: 5000
dockerRegistrySecurePort: 5443
dockerInsecureRegistryAddress: "{{dockerRegistryDomain}}:{{dockerRegistryInsecurePort}}"
dockerInsecureRegistrySubnet: "10.96.0.0/12"
jenkinsMasterInsecurePort: 8080
nexusInsecurePort: 8081
nexusRegistryUserName: "admin" 
nexusRegistryUserPass: "admin"
chartmuseumInsecurePort: 8082
chartmuseumUserName: "admin"
chartmuseumUserPass: "admin"
nfsServer: 192.168.56.89
nfsExportedPath: "/nfs-k8s"